---
- name: Instalar requsitos para k8s
  hosts: all
  connection: ssh
  gather_facts: no
  become: true
  remote_user: ubuntu
  become_method: sudo

  tasks:
    - name: Habilitando Modulos do Kernel
      shell: 
        cmd: | 
          cat > /etc/modules-load.d/k8s.conf  << EOF
          br_netfilter
          ip_vs
          ip_vs_rr
          ip_vs_sh
          ip_vs_wrr
          nf_conntrack_ipv4
          overlay
          EOF

    - name: Habilitando Forward no iptables
      shell:
        cmd: |
          cat > /etc/sysctl.d/k8s.conf  << EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          EOF

    - name: Ativando configuracoes
      shell: 
        cmd: |
          sysctl --system
          modprobe br_netfilter

  
    - name: Instalando pacotes necessarios ao k8s 
      ansible.builtin.apt:
        name:
        - apt-transport-https 
        - ca-certificates 
        - curl
        - gnupg
        - gnupg2
        - lsb-release
        state: present
        update_cache: yes

    - name: Instalando containerd
      ansible.builtin.apt:
        name: 
        - containerd
        update_cache: yes

    - name: Dir para configs containerd
      file:
        path: /etc/containerd
        state: directory
         
      
    - name: Habilitando Forward no iptables
      shell:
        containerd config default > /etc/containerd/config.toml
      notify: 
      - Restart Containerd
    
    - name: Restart Containerd
      service:
        name: containerd
        enabled: yes
      notify: 
      - Restart Containerd

    - name: Repositorio do kubernetes
      block:
        - name: Adicionando Chave publica para  Repo K8s
          ansible.builtin.get_url:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

        - name: Adicionando Repo K8s
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
            state: present
    
    - name: Instalar kubelet, kubeadm e kubectl 
      ansible.builtin.apt: 
        name:
        - kubelet=1.24*
        - kubeadm=1.24*
        - kubectl=1.24*
        update_cache: yes

    - name: kubelet service enabled
      service:
        name: kubelet
        enabled: yes
  

  handlers: 
  - name: Restart Containerd
    service:
      name: containerd
      state: restarted
      