---
- hosts: _control_plane
  become: yes
  gather_facts: false
  tasks:
    - name: Pegando comando join 
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Setando env com comando join
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: _workload
  become: yes
  tasks:
    - name: Integrando Node no cluster
      shell: "{{ hostvars[groups['_control_plane'][0]].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt